# ROLLBACK SCRIPT - Generated 20251003_151236
# Run this script to undo the file organization
$ErrorActionPreference = "Stop"
Write-Host "Rolling back file organization..." -ForegroundColor Yellow

Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_backup.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_backup.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_current_materials.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_current_materials.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_db_status.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_db_status.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_excel_body_names.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_excel_body_names.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_hr4977.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_hr4977.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_lowercase_bodies.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_lowercase_bodies.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_opals.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_opals.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_ring_data.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_ring_data.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\checks\check_system.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\check_system.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\maintenance\run_fix.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\run_fix.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\maintenance\find_any_lowercase.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\find_any_lowercase.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\maintenance\find_lowercase_rings.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\find_lowercase_rings.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\maintenance\fix_body_names.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\fix_body_names.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\maintenance\fix_material_names.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\fix_material_names.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\import_excel_to_database.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\import_excel_to_database.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\init_database.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\init_database.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\create_bubble_database.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\create_bubble_database.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\migrate_excel_to_db.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\migrate_excel_to_db.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\database\add_hotspot_columns.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\add_hotspot_columns.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\cleanup\clear_user_data_db.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\clear_user_data_db.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\tools\check_versions.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\check_versions.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\tools\process_journals.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\process_journals.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\build\build_executable.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\build_executable.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\build\verify_installer.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\verify_installer.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\installer\config_installer.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\config_installer.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\installer\config_installer.bat" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\config_installer.bat" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\scripts\testing\test_auto_scan.py" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\test_auto_scan.py" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\ENHANCED_RING_FINDER_IMPLEMENTATION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\ENHANCED_RING_FINDER_IMPLEMENTATION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\ENHANCED_RING_FINDER.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\ENHANCED_RING_FINDER.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\GALAXY_DATABASE_IMPLEMENTATION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\GALAXY_DATABASE_IMPLEMENTATION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\RING_DENSITY_IMPLEMENTATION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\RING_DENSITY_IMPLEMENTATION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\JOURNAL_PATH_CHANGE_IMPLEMENTATION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\JOURNAL_PATH_CHANGE_IMPLEMENTATION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\JOURNAL_PATH_IMPLEMENTATION_COMPLETE.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\JOURNAL_PATH_IMPLEMENTATION_COMPLETE.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\LOGGING_IMPLEMENTATION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\LOGGING_IMPLEMENTATION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\MIGRATION_NOTES.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\MIGRATION_NOTES.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\ICON_STANDARDS.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\ICON_STANDARDS.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\implementation\INSTALLER_COMPLETENESS_CHECK.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\INSTALLER_COMPLETENESS_CHECK.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\debug\RING_SEARCH_ANALYSIS.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\RING_SEARCH_ANALYSIS.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\debug\RING_SEARCH_SORT_ORDER_ANALYSIS.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\RING_SEARCH_SORT_ORDER_ANALYSIS.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\debug\RING_FINDER_DEBUG_SESSION_SUMMARY.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\RING_FINDER_DEBUG_SESSION_SUMMARY.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\debug\JOURNAL_PATH_BUG_ANALYSIS.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\JOURNAL_PATH_BUG_ANALYSIS.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\debug\OLD_ANNOUNCEMENT_BUG_ANALYSIS.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\OLD_ANNOUNCEMENT_BUG_ANALYSIS.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\features\CONFIG_MANAGEMENT.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\CONFIG_MANAGEMENT.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\features\INSTALLER_INTEGRATION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\INSTALLER_INTEGRATION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\features\INSTALLER_PROCESS_HANDLING.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\INSTALLER_PROCESS_HANDLING.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\features\REPORTS_PROTECTION.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\REPORTS_PROTECTION.md" -Force
Move-Item -Path "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\docs\features\SMART_UNINSTALLER_README.md" -Destination "D:\My Apps Work Folder\Elitemining Working folder\Releases\EliteMining-Dev\app\SMART_UNINSTALLER_README.md" -Force

Write-Host 'Rollback complete!' -ForegroundColor Green
Write-Host 'Files restored to original locations.' -ForegroundColor Green
